#!/bin/bash

set_default_editor() {
    git config --global core.editor 'vim'
    echo 'export EDITOR=vim' >> ~/.bashrc
    echo 'export VISUAL=vim' >> ~/.bashrc
    echo 'export TZ=Asia/Seoul' >> ~/.bashrc
}

set_default_editor
uv run marimo edit